// Generated by scripts/manifest.mjs — do not edit by hand.
// Run `pnpm manifest` after dropping files into public/feed or public/work/<slug>.

export type Asset = {
  src: string;
  title: string;
  date: string | null;
  width: number;
  height: number;
};

export const feedAssets: Asset[] = [];

export const workAssets: Record<string, Asset[]> = {};
