// Generated by scripts/manifest.mjs — do not edit by hand.
// Run `pnpm manifest` after dropping files into public/feed or public/work/<slug>.

export type Asset = {
  src: string;
  title: string;
  date: string | null;
  width: number;
  height: number;
};

export const feedAssets: Asset[] = [
  {
    "src": "/feed/2025-07-pixel-soccer.png",
    "title": "Pixel soccer",
    "date": "2025-07",
    "width": 1400,
    "height": 1000
  },
  {
    "src": "/feed/2025-08-experiments-index.png",
    "title": "Experiments index",
    "date": "2025-08",
    "width": 1400,
    "height": 1000
  },
  {
    "src": "/feed/2025-09-hitmans-library.png",
    "title": "Hitmans library",
    "date": "2025-09",
    "width": 1400,
    "height": 1000
  },
  {
    "src": "/feed/2025-10-damilares-skills.png",
    "title": "Damilares skills",
    "date": "2025-10",
    "width": 1400,
    "height": 1000
  },
  {
    "src": "/feed/2025-11-sylvan-signal-mark.gif",
    "title": "Sylvan signal mark",
    "date": "2025-11",
    "width": 1920,
    "height": 1080
  },
  {
    "src": "/feed/2025-11-sylvan-site.png",
    "title": "Sylvan site",
    "date": "2025-11",
    "width": 1400,
    "height": 1000
  },
  {
    "src": "/feed/2025-12-chessever-case.png",
    "title": "Chessever case",
    "date": "2025-12",
    "width": 1400,
    "height": 1000
  },
  {
    "src": "/feed/2025-12-sylvan-case.png",
    "title": "Sylvan case",
    "date": "2025-12",
    "width": 1400,
    "height": 1000
  },
  {
    "src": "/feed/2026-01-portfolio-v1.png",
    "title": "Portfolio v1",
    "date": "2026-01",
    "width": 1400,
    "height": 1000
  },
  {
    "src": "/feed/2026-02-chessever-app.jpg",
    "title": "Chessever app",
    "date": "2026-02",
    "height": 4320,
    "width": 7680
  }
];

export const workAssets: Record<string, Asset[]> = {
  "chessever": [
    {
      "src": "/work/chessever/01-featured.jpg",
      "title": "Featured",
      "date": null,
      "height": 4320,
      "width": 7680
    }
  ],
  "damilares-skills": [
    {
      "src": "/work/damilares-skills/01-site.png",
      "title": "Site",
      "date": null,
      "width": 1400,
      "height": 1000
    }
  ],
  "endgame-mobile": [
    {
      "src": "/work/endgame-mobile/01-board.svg",
      "title": "Board",
      "date": null,
      "width": 390,
      "height": 844
    },
    {
      "src": "/work/endgame-mobile/02-browse.svg",
      "title": "Browse",
      "date": null,
      "width": 390,
      "height": 844
    },
    {
      "src": "/work/endgame-mobile/03-puzzles.svg",
      "title": "Puzzles",
      "date": null,
      "width": 390,
      "height": 844
    },
    {
      "src": "/work/endgame-mobile/04-profile.svg",
      "title": "Profile",
      "date": null,
      "width": 390,
      "height": 844
    }
  ],
  "hitmans-library": [
    {
      "src": "/work/hitmans-library/01-site.png",
      "title": "Site",
      "date": null,
      "width": 1400,
      "height": 1000
    },
    {
      "src": "/work/hitmans-library/02-desktop-top.png",
      "title": "Desktop top",
      "date": null,
      "width": 1440,
      "height": 900
    },
    {
      "src": "/work/hitmans-library/03-scroll-25.png",
      "title": "Scroll 25",
      "date": null,
      "width": 1440,
      "height": 900
    },
    {
      "src": "/work/hitmans-library/04-scroll-50.png",
      "title": "Scroll 50",
      "date": null,
      "width": 1440,
      "height": 900
    },
    {
      "src": "/work/hitmans-library/05-scroll-75.png",
      "title": "Scroll 75",
      "date": null,
      "width": 1440,
      "height": 900
    },
    {
      "src": "/work/hitmans-library/06-detail.png",
      "title": "Detail",
      "date": null,
      "width": 720,
      "height": 450
    },
    {
      "src": "/work/hitmans-library/07-mobile-top.png",
      "title": "Mobile top",
      "date": null,
      "width": 430,
      "height": 932
    },
    {
      "src": "/work/hitmans-library/08-mobile-mid.png",
      "title": "Mobile mid",
      "date": null,
      "width": 430,
      "height": 932
    },
    {
      "src": "/work/hitmans-library/09-mobile-low.png",
      "title": "Mobile low",
      "date": null,
      "width": 430,
      "height": 932
    }
  ],
  "pixel-soccer": [
    {
      "src": "/work/pixel-soccer/01-site.png",
      "title": "Site",
      "date": null,
      "width": 1400,
      "height": 1000
    }
  ],
  "sylvan": [
    {
      "src": "/work/sylvan/01-featured.gif",
      "title": "Featured",
      "date": null,
      "width": 1920,
      "height": 1080
    },
    {
      "src": "/work/sylvan/02-desktop-top.png",
      "title": "Desktop top",
      "date": null,
      "width": 1440,
      "height": 900
    },
    {
      "src": "/work/sylvan/03-mobile.png",
      "title": "Mobile",
      "date": null,
      "width": 430,
      "height": 932
    }
  ],
  "workbench": [
    {
      "src": "/work/workbench/01-site.png",
      "title": "Site",
      "date": null,
      "width": 1400,
      "height": 1000
    }
  ]
};
